#!/usr/bin/env bash
# Bash script that will display information about subdomains

display_domain () {
	domain=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $domain" | awk '{print "The subdomain "$1" is a "$2" record and points to "$3""}'
}

if [ "$#" == "1" ]
then
	display_domain "$1" "www"
	display_domain "$1" "lb-01"
	display_domain "$1" "web-01"
	display_domain "$1" "web-02"

else
	display_domain "$1" "$2"
fi
