#!/usr/bin/env bash

# Install nginx on your web-01 server
sudo apt-get update
sudo apt-get -y install ngnix
sudo chown -R /var/www/html/
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service ngnix restart
