#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

apt-get update
apt-get -y upgrade
apt-get -y install haproxy

fname="frontend myfrontend"
fbind="bind *:80"
fdef="default_backend myservers"
front="$fname\n\t$fbind\n\t$fdef"

bname="backend myservers"
balgo="balance roundrobin"
bserver1="server web1 54.209.251.89:80 check"
bserver2="server web2 54.147.180.101:80 check"
back="$bname\n\t$balgo\n\t$bserver1\n\t$bserver2"

sed -i "$ a $front\n$back" /etc/haproxy/haproxy.cfg

sudo service haproxy start
