#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times.
# other method : printf 'Best School\n%.0s' {1..10}
#for i in {1..10}
#do
#    echo "Best School"
#done


for ((i=0; i<10; i++ ))
do
echo "Best School"
done


