#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59

hours=0
i=1
while (( hours <= 12 ))
do
	echo Hour: $hours
	while (( i<60 ))
	do
		echo "$i"
		(( i++ ))
	done
	(( hours++  ))
	i=1

done
