#!/usr/bin/env bash

#Write a Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59

count=0
while (( i<60 ))
do
	if [ "$i" == 60 ]
	then
		(( count++  ))
		i=0
	fi
echo "$i"
(( i++ ))
done
