#!/usr/bin/env bash
#Write a Bash script that gives you information about the school file.

if [ -e "school" ]
then
	echo "school file exist"
	if [ -s "school" ]
	then
		echo "school file is not empty"
	else
		echo "school file isempty"
	fi

	if [ -f "school" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
