#!/usr/bin/env bash
# Script that configure firewall
sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw enable
