#!/usr/bin/env bash
# Nginx is running as the nginx user
pkill -f apache2
chmod 700 /etc/nginx/nginx.conf
chown -R nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
